language: scala
scala:
    - "2.11.7"

jdk:
    - oraclejdk8

branches:
  only:
    - master

script: "sbt compile test"

deploy:
  provider: script
  script: "sbt stage deployHeroku"
  skip_cleanup: true
  on:
    branch: master

