language: scala
scala:
  - "2.11.8"

jdk:
  - oraclejdk8

node_js:
  - "4.2.2"

branches:
  only:
    - master

script:
  - npm install
  - sbt compile coverage test coverageReport codacyCoverage

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

deploy:
  provider: script
  script:
    - sbt stage deployHeroku
  skip_cleanup: true
  on:
    branch: master

# reusing sbt cache in container based infrastructure on travis
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/